@baseUrl = https://localhost:7164

###Rode em Https 

###MOTO

### 🟢 GET - Listar todas as motos
GET {{baseUrl}}/api/Moto
Accept: application/json

### 🔵 POST - Criar uma nova moto
POST {{baseUrl}}/api/Moto
Content-Type: application/json

{
  "id": 1,
  "nome": "mottu",
  "tag": "alomottu2",
  "placa": "1236784"
}

### 🟡 GET - Obter moto por ID
GET {{baseUrl}}/api/Moto/1
Accept: application/json

### 🟠 PUT - Atualizar moto por ID
PUT {{baseUrl}}/api/Moto/1
Content-Type: application/json

{
  "id": 1,
  "nome": "Honda atualizado",
  "tag": "aloHonda123",
  "placa": "2345"
}

### 🔴 DELETE - Remover moto por ID
DELETE {{baseUrl}}/api/Moto/1
Accept: application/json


###USUARIO


### 🟢 GET - Listar todos os usuários
GET {{baseUrl}}/api/Usuario
Accept: application/json

### 🔵 POST - Criar um novo usuário
POST {{baseUrl}}/api/Usuario
Content-Type: application/json

{
  "id": 1,
  "email": "usuario@email.com",
  "senha": "123456"
}

### 🟡 GET - Obter usuário por ID
GET {{baseUrl}}/api/Usuario/1
Accept: application/json

### 🟠 PUT - Atualizar usuário por ID
PUT {{baseUrl}}/api/Usuario/1
Content-Type: application/json

{
  "id": 1,
  "email": "usuario@atualizado.com",
  "senha": "novaSenha123"
}

### 🔴 DELETE - Remover usuário por ID
DELETE {{baseUrl}}/api/Usuario/2
Accept: application/json


###SETOR


### 🟢 GET - Listar todos os setores
GET {{baseUrl}}/api/Setor
Accept: application/json

### 🔵 POST - Criar um novo setor
POST {{baseUrl}}/api/Setor
Content-Type: application/json

{
  "id": 1,
  "nome": "Setor 2",
  "capacidade": 2000
}

### 🟡 GET - Obter setor por ID
GET {{baseUrl}}/api/Setor/1
Accept: application/json

### 🟠 PUT - Atualizar setor por ID
PUT {{baseUrl}}/api/Setor/1
Content-Type: application/json

{
  "id": 1,
  "nome": "Setor Atualizado",
  "capacidade": 2500
}

### 🔴 DELETE - Remover setor por ID
DELETE {{baseUrl}}/api/Setor/1
Accept: application/json


###ESTABELECIMENTO


### 🟢 GET - Listar todos os estabelecimentos
GET {{baseUrl}}/api/Estabelecimento
Accept: application/json

### 🔵 POST - Criar um novo estabelecimento
POST {{baseUrl}}/api/Estabelecimento
Content-Type: application/json

{
  "id": 1,
  "nome": "Estabelecimento 2",
  "tamanho": 100
}

### 🟡 GET - Obter estabelecimento por ID
GET {{baseUrl}}/api/Estabelecimento/1
Accept: application/json

### 🟠 PUT - Atualizar estabelecimento por ID
PUT {{baseUrl}}/api/Estabelecimento/1
Content-Type: application/json

{
  "id": 1,
  "nome": "Estabelecimento Atualizado",
  "tamanho": 120
}

### 🔴 DELETE - Remover estabelecimento por ID
DELETE {{baseUrl}}/api/Estabelecimento/1
Accept: application/json
